# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d983d34a8b73b9496418490b35c04ba6"
name = "wishlist-app"
handle = "wishlist-app-132"
application_url = "https://specification-island-gary-handbags.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brtzzi-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://specification-island-gary-handbags.trycloudflare.com/auth/callback",
  "https://specification-island-gary-handbags.trycloudflare.com/auth/shopify/callback",
  "https://specification-island-gary-handbags.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
